### ISSUE TITLE
Redesign Popup.

### ISSUE THREAD

**Issue by saavran** [Anna-Assistant/Anna#108]
![help page](https://user-images.githubusercontent.com/22423976/34455281-a26f1f88-eda1-11e7-941a-8baf9d21535c.png)
![main page](https://user-images.githubusercontent.com/22423976/34455282-a2ac79dc-eda1-11e7-98af-246677085eaf.png)
![white](https://user-images.githubusercontent.com/22423976/34455462-be82dc24-eda5-11e7-81cd-7162eeec5da9.png)

Pop up design should be changed to the above design.

- Icons should be consistent.
- use same colours as given above.
- In need of images check on zulip chat or comment below.

**Comment by saavran** [comment]
design it like the pictures shown above.

**Comment by lalitmee** [comment]
@saavran Can you provide me the exact color codes and fonts, which you have used in designing?

**Comment by gauthamzz** [comment]
The color code is the same as the ones used in elate folder.

**Comment by lalitmee** [comment]
Actually, I have made the head of the Popup. After that, I am not getting what is happening. And I don't want to disturb the structure of the project. May I create a PR for this?
![screenshot from 2017-12-31 14-34-42](https://user-images.githubusercontent.com/10762218/34460555-c4bfe28e-ee37-11e7-9415-9a4bbf1fc1bd.png)

**Comment by gauthamzz** [comment]
Its slightly slimmer 
Use the earlier toggle button which was already there . It looks better than this.
The header is non rectangular.
The see more part is in a footer with a bit of shadow at the bottom of both the pages.
Send whole. The design will be awkward only half way. You can send pr so that I can check but won't merge

**Comment by lalitmee** [comment]
Ok, then I can try to do the things which I can do. Can you tell me the fonts used in the footer section of the image? In **See More**, **Docs**, etc.

**Comment by gauthamzz** [comment]
All of them Segoe UI light is the font used everywhere

**Comment by gauthamzz** [comment]
Issue is almost solved. 

Pop up size is too large. Other than that it looks good. so closing this issue
