### ISSUE TITLE
Add articles anna got featured

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#116]
make a file featured.md and add the links in website of places where anna got featured 

 Articles where anna got featured

https://www.techypin.info/tech-updates/software-updates/free-voice-assistant-google-crome/

http://www.gotowebsites.info/2017/11/talking-anna-assistant-you-get-stuff-faster-on-google-chrome/#.WkkJ-3WWa00

 https://serkangundogdu13.blogspot.in/2017/11/google-chrome-icin-ses-asistan-anna.html?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed:+SerkanGndodu+(Serkan+G%C3%BCndo%C4%9Fdu)

http://www.thewindowsclub.com/anna-assistant-voice-google-chrome

http://techpp.com/2017/11/10/anna-assistant-voice-assistant-chrome/

**Comment by ananya** [comment]
i would like to take this issue

**Comment by gauthamzz** [comment]
assigned to @ananya-agrawal

**Comment by gauthamzz** [comment]
Solved for adding in website . #120 
Readme left
