### ISSUE TITLE
Open lyrics of a song

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#121]
When user says "lyrics of song", a new tab should be opened with lyrics.

It should be implemented like youtube is implemented. The browser should display the lyrics not search for lyrics in some lyrics website.
Comment before starting to work on this issue.

**Comment by vikramnr** [comment]
@gauthamzz So in a new tab with lyrics which can be displayed from any website?

**Comment by gauthamzz** [comment]
Website if your choice.

**Comment by gauthamzz** [comment]
@vikramnr  are you working on this ?

**Comment by vikramnr** [comment]
@gauthamzz  Yeah sure I'll work on this

**Comment by gauthamzz** [comment]
@vikramnr update on this?

**Comment by savannahar68** [comment]
we can use this API  https://developer.musixmatch.com/documentation  if you are okay with it @gauthamzz  if you are ok with it then please register the app and send me the API key, ill add this feature tonight

**Comment by gauthamzz** [comment]
We should open a website, not use an api 
If we use api where will we display

**Comment by dotcomboom** [comment]
Made a pull request. The intent uses Google's I'm Feeling Lucky feature.
https://github.com/Anna-Assistant/Anna/pull/154

**Comment by gauthamzz** [comment]
its merged thank you :smile:
