### ISSUE TITLE
Reduce pop up size

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#122]
The pop up size is too large relative to the screen size.
The settings ,help buttons also are too large

Reduce the size of pop up.
Follow up of #108.

**Comment by pradeepgangwar** [comment]
I will fix this .

**Comment by lalitmee** [comment]
@pradeepgangwar Are you fixing this?

**Comment by pradeepgangwar** [comment]
I am out .... Probably try it tomorrow. You can try and send a PR If u would like to fix else I will do it.

**Comment by lalitmee** [comment]
Actually, I leave it to you. You do this, I have another issue to solve. Okk.
