### ISSUE TITLE
form me on github hyperlink not working

### ISSUE THREAD

**Issue by Anupam-dagar** [Anna-Assistant/Anna#13]
Although hyperlink is there, but nothing is happening on clicking it.

**Comment by gauthamzz** [comment]
I need more sleep :smile: I'll fix after that.
Install and see it

**Comment by Anupam-dagar** [comment]
yeah i'll fix, I opened the issue in wrong repo :stuck_out_tongue:

**Comment by gauthamzz** [comment]
Both are same only, we used the same webpage for extension home page( the one you see when extension opens) and website.
The folder elate contains the website in this repo. :smile:
