### ISSUE TITLE
change hot word detecting method

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#130]
Change hot word detection metod to snowboy 

https://github.com/Kitt-AI/snowboy

So user needs to give audio in the beg.

Add a voice of user in a folder named "Trigger" --> user saying hey anna
Remove this file from .gitignore
Apply this as the word detection metod for anna.
Do start recognition using webkit speech api only aftet that

**Comment by rudransh1** [comment]
Can I work on this issue

**Comment by lalitmee** [comment]
Yeah, why not. Go ahead.

**Comment by rudransh1** [comment]
What prerequisite knowledge do I require for this?
@lalitmee  @gauthamzz

**Comment by lalitmee** [comment]
I think all the steps are mentioned in the issue. You can take help from there.

**Comment by rudransh1** [comment]
Okay

**Comment by gauthamzz** [comment]
Update ?

**Comment by rudransh1** [comment]
I need more time
Will update tomorrow!

**Comment by gauthamzz** [comment]
Come on Zulip of opencode

**Comment by gauthamzz** [comment]
@hacker1x1x1 update

**Comment by rudransh1** [comment]
please unassign me this issue!... @gauthamzz 
I could not do this...
Let anyone else take this up
