### ISSUE TITLE
Improve docs 

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#131]
Improve https://github.com/Anna-Assistant/Anna/blob/master/docs/HowItWorks.md

Increase number of examples for each part
consistent styling is required

**Comment by nocoderhere** [comment]
I would like to contribute to this. A little suggestion, is it okay if we move the contents of `HowItWorks.md` to `README.md` just like its done [here](https://github.com/swapagarwal/JARVIS-on-Messenger) for another personal assistant. 

Edit: Also, do you want to call Anna as Anna, ANNA or **ANNA** as all 3 are used in the docs. I have made many tiny changes to the docs, but when I try to "publish branch" it says I do not have access. Am I doing something wrong or do you have to authorize something? (this is my first time on Github)

**Comment by gauthamzz** [comment]
Use Anna.

Yeah you can make a table like that in readme. But how it works is for details. 

You can only send pull request. Not make direct changes when you don't own the repo. So fork and make changes then send pull request.
