### ISSUE TITLE
Make a demo video on Youtube

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#132]
Make a Demo video and upload on YouTube. 
Minimum duration 30 seconds

For opencode Participants
---------------------------------
Without editing ---> medium 30 points
with ediiting --> Hard 50 points

Any number of particapants can do this.

**Comment by Panda2498** [comment]
What kind of demo video would you like to have, what contents should it have?

**Comment by gauthamzz** [comment]
A video demo of using Anna. About how it works and all the things it can do.

More like a promotional video. You are free to use your creativity.

**Comment by Panda2498** [comment]
I should make it using screen recorder, right?

**Comment by gauthamzz** [comment]
way of making is your choice. You can use a dslr if you want :smile: 

This is for promoting the product. More like a trailer or tech review.

**Comment by Panda2498** [comment]
I will submit the video by tomorrow. In which section do I upload it.

**Comment by gauthamzz** [comment]
upload on youtube and put link over here.

**Comment by Panda2498** [comment]
https://youtu.be/tGwDLcLavK0

**Comment by gauthamzz** [comment]
Thats pretty good. Can you add the link in readme. 
It was a bit slow in the begining(It would have been better if we made it faster)  but then it gets real good at the end.

**Comment by Panda2498** [comment]
Actually! Net speed sucks!
