### ISSUE TITLE
star this repo

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#134]
post screenshot

Also go to chrome webstore and rate this extension 😈

**Comment by mubaris** [comment]
![screenshot from 2018-01-12 00-00-17](https://user-images.githubusercontent.com/13871723/34840663-aee233e8-f72b-11e7-804e-b04032d4e321.png)

Sir, I have starred the repository. Please give me points

**Comment by ananya** [comment]
![a](https://user-images.githubusercontent.com/33188930/34840684-bffa5732-f72b-11e7-81a8-d0314454bf4d.png)

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34840750-f0608018-f72b-11e7-8800-28aeb50b59c6.png)

**Comment by marshallKR7** [comment]
![screenshot-2018-1-12 anna-assistant anna](https://user-images.githubusercontent.com/28799332/34840763-fe27fc94-f72b-11e7-87a0-32b3d72c182b.png)

**Comment by mubaris** [comment]
If you star the repo 2 times, you will get 20 points

**Comment by rahulkumaran** [comment]
![screenshot from 2018-01-12 00-09-15](https://user-images.githubusercontent.com/26206171/34841026-dd6cbbb0-f72c-11e7-978c-70b0d89e58ae.png)

**Comment by GOVINDDIXIT** [comment]
![captured](https://user-images.githubusercontent.com/32304546/34840968-b611b4da-f72c-11e7-825d-e031eab4eecb.PNG)

**Comment by lalitmee** [comment]
![screenshot from 2018-01-12 00-12-51](https://user-images.githubusercontent.com/10762218/34841196-6d464968-f72d-11e7-99e6-a05e4025eae5.png)

**Comment by Jigar3** [comment]
![screenshot_2018-01-12-00-18-10-220_com android chrome](https://user-images.githubusercontent.com/32068121/34841394-2659ff12-f72e-11e7-80f9-763bb10f9be2.png)

**Comment by adityaraj-xtc** [comment]
![3](https://user-images.githubusercontent.com/34164978/34843243-ea4fc190-f733-11e7-96f4-36f2247c8ec0.png)

**Comment by adiagg2000** [comment]
![screenshot 36](https://user-images.githubusercontent.com/33027339/34843377-4c520cf4-f734-11e7-90ed-f712b09843fd.png)

**Comment by ProBeta1** [comment]
![screenshot-2018-1-12 anna-assistant anna](https://user-images.githubusercontent.com/33081197/34843720-48c02372-f735-11e7-8817-d5295a899eed.png)

**Comment by aryan-harsh** [comment]
![image](https://user-images.githubusercontent.com/35261946/34846464-4853e83e-f73e-11e7-851f-52c34f69bf09.png)

**Comment by AK-007** [comment]
![screenshot 55](https://user-images.githubusercontent.com/26346816/34848254-25994dba-f744-11e7-91c0-1415af7ad353.png)

**Comment by strikertanmay** [comment]
![screenshot from 2018-01-12 13-44-36](https://user-images.githubusercontent.com/32292953/34865437-c90cd1d8-f79e-11e7-89bc-170e4f62c964.png)

**Comment by vvvinamer** [comment]
![screenshot 32](https://user-images.githubusercontent.com/35339278/34868683-9ca10022-f7aa-11e7-876a-48dee9585768.png)

**Comment by arshjat** [comment]
![aa](https://user-images.githubusercontent.com/29671220/34869663-9c23c866-f7ad-11e7-990e-ded111347710.png)

**Comment by AlphaCholera** [comment]
![screenshot from 2018-01-12 21-12-06](https://user-images.githubusercontent.com/33174671/34870123-2f8b16da-f7af-11e7-9fd3-00cb9c06fa8b.png)

**Comment by aadixiiita** [comment]
![screenshot_20180112-181419](https://user-images.githubusercontent.com/34688457/34875732-7e56a724-f7c4-11e7-81dd-ffacb51520f3.png)

**Comment by lalitmee** [comment]
Hey @gauthamzz congratulations for 72 stars on the repo. But I am not getting that in one how this happened?

**Comment by gauthamzz** [comment]
its an opensource event form IIIT Allahabad, to prmote opensource. If anyone from your college wants to join refer them. Its a great place to start Github @opencode18. Opencode is its name.

**Comment by Anubhav2000** [comment]
![capture](https://user-images.githubusercontent.com/33462670/34887398-5c026c6c-f7ec-11e7-9a56-a7c44c2bc738.PNG)

**Comment by Panda2498** [comment]
![anna](https://user-images.githubusercontent.com/34282889/34888385-26ae0cd4-f7f0-11e7-9f05-f8b911bdcce1.PNG)

**Comment by nikki1016** [comment]
![star3](https://user-images.githubusercontent.com/26041681/34888794-9dcf3792-f7f1-11e7-8c7d-b9d576317e36.png)

**Comment by hiteshpr** [comment]
![opencodestar](https://user-images.githubusercontent.com/19280178/34918588-c13c1986-f97a-11e7-921a-90a45f4074ae.png)

**Comment by Tlazypanda** [comment]
![image](https://user-images.githubusercontent.com/33183263/34921039-a48b43de-f9a2-11e7-9c6e-78fcba1a40cc.png)

**Comment by ekanban** [comment]
![screenshot 26](https://user-images.githubusercontent.com/34866483/34924472-8ae5d328-f9c9-11e7-8297-d59055bd70b9.png)

**Comment by rudransh1** [comment]
![screenshot_20180115-212014](https://user-images.githubusercontent.com/34509429/34950799-30bc1486-fa3a-11e7-80bb-605789382877.jpg)

**Comment by pani-vishal** [comment]
![anna](https://user-images.githubusercontent.com/30634978/34989903-36d8c2aa-faea-11e7-8947-a0099937421b.png)

**Comment by surasnayak** [comment]
Done!
![screenshot from 2018-01-16 23-04-29](https://user-images.githubusercontent.com/21239888/35003076-ad04dd02-fb11-11e7-8d6d-a094e2008933.png)

**Comment by asthemus** [comment]
![firefox_screenshot_2018-01-18t15-52-37 360z](https://user-images.githubusercontent.com/34709632/35081319-94aff43e-fc39-11e7-925c-1e5cf4cf469d.png)

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/29673845/35279394-f93799fe-001a-11e8-9dc6-e430a1a0f5e9.png)
