### ISSUE TITLE
add more exmaples in readme

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#135]
add more examples in the readme table
the examples can be seen in the how it works faq question

**Comment by GOVINDDIXIT** [comment]
i will do it

**Comment by ananya** [comment]
will like to do it

**Comment by gauthamzz** [comment]
assigened to @GOVINDDIXIT

**Comment by GOVINDDIXIT** [comment]
@gauthamzz  I have send the PR .Do I have to add more examples or it is fine

**Comment by gauthamzz** [comment]
see the review i made. I had requested some changes

**Comment by GOVINDDIXIT** [comment]
sir , where is the review 😕
