### ISSUE TITLE
Change Anna's voice 

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#141]
Last few lines of background js ,change from the present robotic voice to a much more futuristic sound

**Comment by pani-vishal** [comment]
I'd like to take this

**Comment by gauthamzz** [comment]
yeah sure. try various types and send me samples. Ill select on zulip.

**Comment by pani-vishal** [comment]
Sure! I'll get to this tomorrow.

**Comment by gauthamzz** [comment]
@falconis are you able to do this ?

**Comment by pani-vishal** [comment]
Actually Anna isn't working for me.
It won't hear what I say. Could you please look into it? :smiley:  @gauthamzz

**Comment by gauthamzz** [comment]
lol, use the latest code and use a microphone. Still not working check if your microphone is working. Try something like recoding audio on browser. 
See if permssions are given.
Still now working, reload it.

**Comment by gauthamzz** [comment]
This issue is open and still not solved

**Comment by vikasgola** [comment]
@gauthamzz I have opened a pull request for this. Please review.

**Comment by gauthamzz** [comment]
on it :smile:
