### ISSUE TITLE
feature  delete cache 

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#145]

**Comment by savannahar68** [comment]
I want to work on this, can you provide more detail as in when the cache should be deleted? Like are we going to provide some button for it, or some specific time or some other approach you have in your mind?

**Comment by gauthamzz** [comment]
broswer cache like "login details etc"

**Comment by savannahar68** [comment]
Ok got it, will add it by tomorrow

**Comment by savannahar68** [comment]
So we have to delete only the cache of the same app right ? and not the entire browser (becase that cannot be done and will be a huge bug) offcoouse i can redirect it to that page 
Let me know which one do you want

**Comment by gauthamzz** [comment]
entire browser is what people normally do

**Comment by gauthamzz** [comment]
Thanks
