### ISSUE TITLE
Make trigger shortcut key

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#15]
Anna presently works on a speech trigger “hey” instead it should work when a trigger like a shortcut key is pressed. Code is in background.js

**Comment by anandwana001** [comment]
@gauthamzz I would like to contribute to this

**Comment by gauthamzz** [comment]
assigned to @anandwana001

**Comment by anandwana001** [comment]
@gauthamzz does everything related to this issue is in background.js only?

**Comment by gauthamzz** [comment]
yes, background.js does all the functionalities in a chrome extension. but when a shortcut key is pressed. trigger no longer should be said/ trigger is "hey"

**Comment by anandwana001** [comment]
@gauthamzz we have to work on extension part

**Comment by gauthamzz** [comment]
I was thinking more off like a button in popup.html to enable trigger via voice or shortcut . You can do the shortcut part. The latter will be done as a diffrent pr

**Comment by gauthamzz** [comment]
@anandwana001 are you still working on this?

**Comment by gauthamzz** [comment]
No longer a priority
