### ISSUE TITLE
Change pop up design for help

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#158]
Anna is using landbot.io for help section in pop up.

Remove the previous one and make it more clean.

![deepinscreenshot_select-area_20180625142423](https://user-images.githubusercontent.com/12110844/41840497-80e3077c-7883-11e8-8b16-5f57f8fa25a7.png)

**Comment by rupal16** [comment]
Hey, can I work on this issue?

**Comment by gauthamzz** [comment]
yeah sure

**Comment by gauthamzz** [comment]
any update ?
