### ISSUE TITLE
Make the reply text to be read

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#17]
you need to call speech in fulfilment and say it back in this line https://github.com/Anna-Assistant/Anna/blob/master/background.js#L189

setResponse(); --- Function can be used to say the reponse 

An example of json response is given below.
{
  "id": "",
  "timestamp": "",
  "lang": "en",
  "result": {
    "source": "agent",
    "resolvedQuery": "how to go from Allahabad to Kanpur",
    "action": "",
    "actionIncomplete": false,
    "parameters": {
      "geo-city": [
        "Allahabad",
        "Kanpur"
      ]
    },
    "contexts": [],
    "metadata": {
      "intentId": "",
      "webhookUsed": "false",
      "webhookForSlotFillingUsed": "false",
      "intentName": "maps"
    },
    "fulfillment": {
      "speech": "Opening Google Maps",
      "messages": [
        {
          "type": 0,
          "speech": "Opening Google Maps"
        }
      ]
    },
    "score": 1
  },
  "status": {
    "code": 200,
    "errorType": "success"
  },
  "sessionId": "bfc71263-9db0-4304-a825-94cfffc990c6"
}

**Comment by brainstormm** [comment]
nigga working hard on this project.

**Comment by gauthamzz** [comment]
@brainstormm Stop cracking lame jokes on GitHub, be professional :smile:

**Comment by gautamramuvel** [comment]
Can you please explain the issue even more simpler.

**Comment by gauthamzz** [comment]
When you use Anna . 
You - open Facebook
Anna - you said open Facebook 
Then opening task happens right .

Instead make this 
You - open Facebook 
Anna- opening Facebook 

Given by result.fullfilement.speech as per the json

**Comment by sanketgautam** [comment]
Hi @gauthamzz  I got this one, I'll be working on this issue

**Comment by gauthamzz** [comment]
could you work on one issue at a time, you can do this after finishing the screenshot one. untill then let it be open

**Comment by gautamramuvel** [comment]
Then.. I will take this issue.!

**Comment by gauthamzz** [comment]
solved via commit https://github.com/Anna-Assistant/Anna/commit/82a19a255700da58fcda5e9bd0c0247ca25f3f02 by @gauthamzz
