### ISSUE TITLE
New skill - Show Internet Speed to the user.

### ISSUE THREAD

**Issue by sakshichahal53** [Anna-Assistant/Anna#172]
**Input to Anna :** "Hey, Show Internet Speed".
**Expected Ouput:** A new tab is opened directed at Fast.com showing the results.
We also plan to make Anna speak the internet speed to the user through some web-scraping techniques.

For this, probably we need the access to the Dialogflow files to help us give a better understanding of the project, and also, to create a new skill for Anna.

**Comment by gauthamzz** [comment]
Could you add about this skill in the docs.
