### ISSUE TITLE
New skill - Add high low game to Anna 

### ISSUE THREAD

**Issue by sakshichahal53** [Anna-Assistant/Anna#176]
This skill is a basic high-low game. Guess a number, and Anna will tell you whether the number she has in mind is higher or lower. You will be given a fixed number of guesses. If you guess the correct number before your given number of chances finish you win, else you lose.

**Comment by gauthamzz** [comment]
What should be the words triggering it?

**Comment by sakshichahal53** [comment]
The input could be:
"Hey, Let's play number game."
"Hey, number game."
"Hey, play number game."

**Comment by gauthamzz** [comment]
It's added intent name is `numbergame`

**Comment by sakshichahal53** [comment]
Hi @gauthamzz kindly have a look on the recent commits on the pull request.
