### ISSUE TITLE
New features to be added 

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#18]
Suggestions for new features to added on this thread.

**Comment by srvkmr130** [comment]
Hey this feature can be added: OPEN in safe mode feature 
Where when user tells open in safe mode automatically after surfing, today's record(history) will be deleted from the history panel.
How this is ?

**Comment by gauthamzz** [comment]
Do you mean incognito ?

**Comment by srvkmr130** [comment]
YES !!!

**Comment by srvkmr130** [comment]
it would be like adding more features.

**Comment by gauthamzz** [comment]
okay you can do it :+1:

**Comment by srvkmr130** [comment]
done open in safe mode..

**Comment by sanketgautam** [comment]
Hey! I would like to suggest one, "Youtube Song Lyrics" feature can be added to Anna. I prefer not go with Music recogition APIs as they have poor accuracy, and also incapable to detecting latest songs  (atleast free apis), alternatively, we can use free & open lyrics APIs like [Lyrics.ovh](https://lyricsovh.docs.apiary.io/).

Example call looks like: `https://api.lyrics.ovh/v1/Coldplay/Adventure of a Lifetime` and it'll result the json object containing the lyrics if found, which we can show to the user.

**Points for further discussion:** We can easily identify that a video is song or not by using youtube video API, by looking for `"categoryId": "10"`, but there is no provision to obtain author & song name from a youtubeURL/videoID using Youtube API.

After bit of research, I found this : https://github.com/goto-bus-stop/get-artist-title
It extracts artist & title from a string (may be video title or anything). It may work for signification number of popular videos, but not for all, as the video title not always contains the "Album"/ "Artist Name".

I would like to know your views & suggestions on this feature, or whether it's even worth to implement.

**Comment by gauthamzz** [comment]
If you see Anna YouTube's code. We just search the text using YouTube API and the first answer is shown. I think only a similar approach is needed.

**Comment by sanketgautam** [comment]
@gauthamzz as explained in my previous comment, for our usecase, Youtube API only provide us `categoryID` which can help us to identify the type of video. As per my knowledge & exploration, It does not provide artist or title for any music video as of now.

**Comment by lalitmee** [comment]
Hey, I would like to suggest one. 

It is like **To-Do List** in our browser. We can add tasks by talking to Anna and then Anna can set a reminder and then Anna can alert us that we have to do this at this date or time. 
We can also track the task done and remained. 

I think we can do this. Let me know your opinion on this.

**Comment by gauthamzz** [comment]
We already can set reminders using google calander . We can improve it a bit more.

**Comment by paveethan** [comment]
How about the ability for one to get their own horoscope? i.e 'hello, horoscope for aries'

**Comment by gauthamzz** [comment]
Sounds cool. Send pr

**Comment by paveethan** [comment]
Does anything need to be added in DialogFlow first? I was testing it out the other day but it kept failing, even after being added in the list of intents in tasks.

**Comment by gauthamzz** [comment]
I will add it :smile:
