### ISSUE TITLE
Add tell me a joke feature 

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#26]
Keep an array of jokes and read it back to the user when indent is joke. The work in api.ai is already done 

when user says "tell me a joke" ,  "tell a joke " ,"joke"  or "make me laugh "

**Comment by nvinayvarma189** [comment]
I want to add some good jokes, but I can't find the code related to this issue.Can you please help me?

**Comment by gauthamzz** [comment]
One person is already working on this issue. please work on other issues
