### ISSUE TITLE
Redesign Logo for Anna

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#45]
Looking for minimal, Futuristic logo maybe with some transitions.

**Comment by srvkmr130** [comment]
I will do this.

**Comment by gauthamzz** [comment]
You can suggest it at the comment, more than one people can try

**Comment by srvkmr130** [comment]
ok will do the same....

**Comment by saavran** [comment]
![3d](https://user-images.githubusercontent.com/22423976/34436665-dd07c5ee-ecbd-11e7-8ce5-86a748915d9d.png)
![118a1750321639](https://user-images.githubusercontent.com/22423976/34436666-dd42b3ac-ecbd-11e7-9d47-6a9f9f6dd960.png)
![shadow](https://user-images.githubusercontent.com/22423976/34436667-dd7bb86e-ecbd-11e7-8e4d-c41cab0deda8.png)
![icon](https://user-images.githubusercontent.com/22423976/34436676-e854c0c8-ecbd-11e7-95df-8dbff99d02a9.png)
Aana means  Elephant in malayalam.

**Comment by gauthamzz** [comment]
It's awesome 😍

**Comment by lalitmee** [comment]
@saavran Yeah, great efforts.
