### ISSUE TITLE
Create floating chat

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#61]
- Add a small chat like button at the right corner of the screen (movable in the future)
- When the user clicks the button a chat with Anna and the user starts, every conversation between user and Anna will be there from that moment.
- This issue requires one to just make the front end of the problem.

The idea is user should be able to see a floating chat at his screen all the time.

**Comment by pradeepgangwar** [comment]
What type of conversation will be there between user and anna. And what is the expected output from Anna (action and text).

**Comment by gauthamzz** [comment]
we only need anna to say things to user for now.
This line https://github.com/Anna-Assistant/Anna/blob/master/background.js#L276 is said back to user now.

I was thinking the same text will be shown to the user.

**Comment by gauthamzz** [comment]
@pradeepgangwar update ?

**Comment by pradeepgangwar** [comment]
I will try it . Meanwhile anybody else willing to work can try it.

**Comment by aadixiiita** [comment]
Can i try this ?

**Comment by gauthamzz** [comment]
yeah sure @aadixiiita 
we want something like this https://codepen.io/slavik10/pen/wadzYe
replace the girls image by anna's logo

**Comment by gauthamzz** [comment]
What’s the status of this issue ?

**Comment by aadixiiita** [comment]
i am working .. i'll give u update shortly..

**Comment by gauthamzz** [comment]
@aadixiiita update?

**Comment by gauthamzz** [comment]
This issue is still unsolved. We are looking for an intercom/Drift like chat instead of the current status symbol.

As Anna replies something, the chat bubble should say what anna says.

![image](https://user-images.githubusercontent.com/12110844/41838674-ab5e7978-787e-11e8-9c58-bb13278dbbb9.png)
