### ISSUE TITLE
crop the image during reverse search and screenshot feature

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#64]
User: "screenshot:
Anna: " you said screenshot"
Anna: " Do you want to crop the image?"
User: "yes"
then a crop the screen before the screenshot page opens

It is preferred to be done inside the page itself. If that is not possible and comes only when in the screenshot page which we have right now. Its also fine.

**Comment by sanketgautam** [comment]
@gauthamzz I'll take this issue

**Comment by gauthamzz** [comment]
assigned to @sanketgautam
