### ISSUE TITLE
Write documentation for Anna

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#74]
Should contain:

How files are arranged
How to add new features
How it works
How to Install

**Comment by srvkmr130** [comment]
This should be done in md format or simply txt ?

**Comment by gauthamzz** [comment]
markdown

**Comment by mmBabol** [comment]
Hi @gauthamzz can I take this issue?? I'm relatively new to open source and would love to work on this

**Comment by gauthamzz** [comment]
Actually @srvkmr130 was working on it. You can talk to him on our channel in zulip . Link in readme and split the work and do it

**Comment by srvkmr130** [comment]
@mmBabol I have done with arrangement of files and how to add new fetaures..You may take the other rest 2,if you wish.Just inform the mentor before taking the issue.

**Comment by mmBabol** [comment]
@srvkmr130 I see you've also done how to Install, I can take the last section "How it works". Is that okay @gauthamzz ? Is it a new md file that I would create for this?

**Comment by gauthamzz** [comment]
Yeah sounds cool

**Comment by gauthamzz** [comment]
@srvkmr130 @mmBabol  can you add the install part which is written in the readme to doc. And remove from readme

**Comment by gauthamzz** [comment]
An FAQ is also needed in Docs.

**Comment by gauthamzz** [comment]
#82 #83 #84 #85 #111 #100 solved issue 
solved by @mmBabol  and @srvkmr130
