### ISSUE TITLE
create Pull Request Template

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#75]
Should check for:-

1. Issue is linked in the commit
2. Proper commit messages are written
3. Refer template of any open source project you like and follow similar

**Comment by lalitmee** [comment]
@gauthamzz what do you think about [this](https://github.com/iiitv/algos/blob/master/CONTRIBUTING.md) template?

**Comment by gauthamzz** [comment]
That's contribution guides we already have that . Just link that it's enough.

**Comment by lalitmee** [comment]
Should I create a link for this template in the **readme.md** file.

**Comment by gauthamzz** [comment]
No. 

See this https://github.com/fossiiita/opencode2017/blob/master/PULL_REQUEST_TEMPLATE.md don't add the last part. And tell them to read the docs once.

**Comment by lalitmee** [comment]
You mean I can add this one. From _code practices_ to _tutorials_. Am I right?

**Comment by gauthamzz** [comment]
The link I send is what we want. It's pull request template it shouldn't be huge. And remove that part of link . Instead make like add relevant images in the comment

**Comment by lalitmee** [comment]
@gauthamzz Can we set up a slack channel for Anna. I know that we have zulip-chat. But I think slack would be more attractive and user-friendly. I just want your opinion.

**Comment by gauthamzz** [comment]
we promote opensource thats why we use zulip. 
zulip is good if you try it. its very fast . I think we will stay with zulip for now.

**Comment by gauthamzz** [comment]
closed at #105 by @lalitmee

**Comment by lalitmee** [comment]
Ok. I was saying because I haven't used Zulip. But no problem. I am adaptable to change. hahaha.

**Comment by gauthamzz** [comment]
I have used slack and discord as well. I think of them two discord is better. But for zulip is the best for our purpose
