### ISSUE TITLE
Show users that voice recognition is working in the system

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#78]
Users might have the voice mute or soundcard problem should know that anna is working properly but rather its a problem of the system.

One way is to show what they say in a text box in pop up 
or if pop up is open and user is not speaking anything a small indicator can also work.
Other ideas are welcome

**Comment by sanketgautam** [comment]
I would say showing text to user in popup will not be good from UX point of view.

When user _"turns on" recognition from the Browser Actions_, then we can start a little icon on the bottom of  them screen, maybe like a little circle (something like go to top/bottom on various websites). 
And when user says something that is identified by Anna then we can change that change that icon or it's color
We may use colours to identify both the phases to users. *For Inactive - Red Icon, For Active Phase - Green Icon or GIF (to make it look alive)* 

**Point for Discussion:** It would be always present on the right corner of the screen, on each webpage user visits. Will that be any issue for users?

**Comment by gauthamzz** [comment]
If we can make the button also enabled and disabled via a new pop up button to activate it,i think it can work.

**Comment by sanketgautam** [comment]
Okay, I'll add a button in popup to set "visibility" of this icon, so that users can toggle between both the versions using that.
@gauthamzz  Should I proceed for implementation?

**Comment by gauthamzz** [comment]
Sounds good assigned to you
