### ISSUE TITLE
Optimise code

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#80]
- Remove redundant code
- The extension increases cpu usage 

Suggest ideas 
- Faster execution of code
- Increase response speed

**Comment by srvkmr130** [comment]
I would like to contribute to some part of it .

**Comment by paveethan** [comment]
I would like to contribute as well:

bff79a853525f00498e4a561cc8e48da4f3202bc
f3194ae9b0de689da416c5964e64fe88377dd4b5

**Comment by gauthamzz** [comment]
Thanks
