### ISSUE TITLE
Feature: Show Anna Status using "Browser Action" Icon

### ISSUE THREAD

**Issue by sanketgautam** [Anna-Assistant/Anna#91]
Currently, we are using content script to inject status icon on each & every webpage user visits and change status icon according to the actions performed by users.

This can further be improvised by leveraging chrome extension's [Browser Action](https://developer.chrome.com/extensions/browserAction), to show current status of Anna. As, it's always available and can easily modified by using Chrome Extension's API.

We can use different Browser Action Icons, for visualizing Anna's current status, which would be better from UX perspective, as well as, for performance (as we don't need to update status on every iteration), we can use some Event Handler for that purpose. Whenever a user performs some actions, only then we need to change the Icon according to the user action.

For more information on Anna's Status, go through this Pull Request: #88 ( Issue: #78 ). If you have any better suggestion, please feel free to discuss & implement.

**Note:** For initial phase, it would be better to have a toggle button in Extension's Popup, so that users have flexibility in switching between both the versions (current & new).

**Comment by gauthamzz** [comment]
I have added this feature in https://github.com/Anna-Assistant/Anna/commit/f8d29d07d09c3fe2aaa8456a0fd53815e2418746

Didn't add a toggle button since it didn't seem needed. 

Red Icon for inactive
Black for Normal
Blue-green theme colour when active

**Comment by sanketgautam** [comment]
Yeah! Seems Good 😃
